### ISSUE TITLE
download_toolkit temp file should be a generated location and just be the toolkit.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#10]
`download_toolkit` seems to place its download directly in `/tmp` when a directory is not specified.

This can lead to issues if there are multiple concurrent executions, ideally a temp location should be used.

In addition the return directory is a sub-directory of the download. This will cause issues as the caller would only assume they have to clean up the returned directory, not one level higher. E.g. an automated test shouldn't have to figure out the full download is one higher.

**Comment by markheger** [comment]
resolved in version 1.0 of streamsx.toolkits
