### ISSUE TITLE
Add check to ensure name is an SPL identifier.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#20]
To ensure that the underlying SPL operator name is actually the name provided by the Python developer and thus the path element in the URL is also the same name, verify that the name is a valid SPL identifier.

**Comment by markheger** [comment]
Is there any function in topolgoy/streamsx that can be called or the rules can be taken from?

**Comment by ddebrunner** [comment]
@markheger Let me check.
