### ISSUE TITLE
Need fixed location for docs.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#24]
The docs were at: https://streamsxendpoint.readthedocs.io/en/1.0.0/

but are now at https://streamsxendpoint.readthedocs.io/en/1.0.1/

Either all versions need to be left up so that links don't become broken, or switch to the common pattern of `https://streamsxendpoint.readthedocs.io/en/stable` and `latest`.

**Comment by markheger** [comment]
there is a fixed location:
http://streamsxendpoint.readthedocs.io/
