### ISSUE TITLE
Remove fixed (4.3.0) version dependency on the SPL toolkit.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#25]
A fixed version for a dependency has the potential to cause future issues, applications will fail if a new release of Streams has for example 4.3.1 released. Should this be changed to a range, either within 4.3.x or 4.3.0-5.0.0 to match the expectation that toolkits are compatible until the major version changes.

https://github.com/IBMStreams/pypi.streamsx.endpoint/blob/develop/package/streamsx/endpoint/_endpoint.py#L19

**Comment by markheger** [comment]
resolved in 1.0.2
