### ISSUE TITLE
Rename json_injection to inject

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#3]
I wonder if `json_injection` should be renamed to `inject`.

A schema parameter could be added, defaulting to `json` that would then allow the potential for different schemes in the future. E.g. passing a structured schema would then just switch the underlying SPL operator to a different kind.

Otherwise we will end up with multiple similar methods with awkward names to differentiate.

**Comment by markheger** [comment]
agree to this approach to use different operators depending on the schema

**Comment by joergboe** [comment]
I wonder if the operators HTTPJSONInjection, HTTPTupleInjection, HTTPBlobInjection ... should be merged
