### ISSUE TITLE
Need to have a required context parameter for endpoint functions.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#6]
Without a context parameter then endpoint is unknown inPython, so a developer has no idea of what URL to use.

**Comment by joergboe** [comment]
If parameter context is applied, parameter contextResourceBase is required too.

**Comment by joergboe** [comment]
Without context parameter:
The lead in for port resources exposed by this operator is the full operator name so that it is unique.
With context parameter:
the lead is context/base name of the operator (without the composite nesting qualifiers)

However the user must know the operator name.

**Comment by ddebrunner** [comment]
The lead in is not guaranteed to be the operator name with a Python application, since it's converted to SPL and the operator may end up being several levels deep in composites.

How it's converted to SPL is an implementation detail that we don't want to guarantee to the user.

**Comment by ddebrunner** [comment]
`contextResourceBase` could be hard coded to something like `application_directory/opt/`_context_  by the wrapper (SPL composite or Python) so that the it's a fixed pattern of how to provide static context files. This simplifies the setup and allows Python apps to add files to a known location.

**Comment by joergboe** [comment]
I would prefer a correction in the internetserver toolkit becuase the current implementation easily leads to difficult errors.
If a developer has more than one internetserver operators and provides` context` parameter one is forced to apply the `contextResourceBase` with the same value to all operators. If the `contextResourceBase` value differs the behaviour depends on the order of the operators.
Therefore I would like to remove the requirement to add the `contextResourceBase` if the context parameter is present for all internetserver operators except `WebContext`.

So finally in this package
- the `contextResourceBase` should be optional paramter with default=none
- the `context` parameter should be mandatory parameter

**Comment by ddebrunner** [comment]
In thinking some more, we may want to have a parameter `contextResources` with default of `None`. (instead of `contextResourceBase`)

If it is set then it is a directory and its contents are copied into `opt/resources/`_context_  and the SPL operator parameter `contextResourceBase` is set correctly.

That avoids forcing the developer to have to make additional steps when it could be done in one.

**Comment by joergboe** [comment]
I prefer the direct solution. I make the contextResourceBase an optional parameter. So the developer must use the parameter only if is required.
I see no advantage to invent another parameter and then make a copy of the data, if an direct solution is possible.

**Comment by ddebrunner** [comment]
`context` parameter is optional in `inject` and `expose`, not mandatory.

**Comment by ddebrunner** [comment]
Setting `context` for inject leads to this:
![image](https://user-images.githubusercontent.com/3769612/65988823-6af3a080-e43d-11e9-88ae-bfae0120e061.png)

This is using the latest toolkit by using `endpoint.download_toolkit()` to get the latest version.

Ideally the package would internally specify its toolkit dependency using: https://streamsxtopology.readthedocs.io/en/latest/streamsx.spl.toolkit.html#streamsx.spl.toolkit.add_toolkit_dependency
Would make it easier to diagnose tooling version mismatches.

**Comment by joergboe** [comment]
The test must use the correct toolkit version.

**Comment by ddebrunner** [comment]
@joergboe Can the package set the required toolkit version as in the comment above.

What is the required toolkit version, I was using the latest.

**Comment by markheger** [comment]
streamsx.spl.toolkit.add_toolkit_dependency should be used to require 4.2.0 and above
Was formerly not possible to add this code since the toolkit was on develop branch only.

**Comment by ddebrunner** [comment]
context in 0.6.0 is still optional.

https://github.com/IBMStreams/pypi.streamsx.endpoint/blob/0.6.0/package/streamsx/endpoint/_endpoint.py#L58

https://github.com/IBMStreams/pypi.streamsx.endpoint/blob/0.6.0/package/streamsx/endpoint/_endpoint.py#L108
