### ISSUE TITLE
What is the purpose of allowing `port` to be specified.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/pypi.streamsx.endpoint#8]
Is there any benefit to specifying `port`?

 It just brings the pain to the developer or Streams admin of having to avoid clashing ports.

These endpoint calls are intended to be only supported with Streams v5 in a Kubernetes environment, using endpoint-monitor. At no point would we be supporting or encouraging direct access to the Jetty operator, so what's the value in having a fixed port?

**Comment by joergboe** [comment]
The port parameter is the significant parameter for the common usage of an embedded jetty.
All operators with the same port number share one jetty if they are fused into one pe.

There might be some exceptional cases where the common usage of a jetty is not preferable. In such cases a defined port != 0 is required.

In most of the cases the setting `port=0` is sufficient and this is the default.

**Comment by ddebrunner** [comment]
So why add complexity for yet to be defined exceptional cases?

With the approach of #7 if needed setting the port can be added later.

Sometimes "less is more", simplify, add additional capability when needed. (YAGNI)

**Comment by ddebrunner** [comment]
The port needs to be set to `0` for the Jetty operator but not exposed as a parameter to the user. The latter has been done, but nothing is being passed to the operator so it's defaulting to port 8080. This will cause port clashes.

**Comment by markheger** [comment]
resolved in 0.5.0
